---
title: "Tide and SLR Impact on CSO Regulators Analysis v2.8"
author: 
- "[Hao Zhang](mailto:hao.zhang@phila.gov)"
- "[Victoria Reis](mailto:victoria.reis@phila.gov)"
date:  "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    css: www/bootstrap_Cerulean.css
runtime: shiny
---

###Objectives
Discuss the impact of observed and projected tide elevations on Philadelphia's Combined Sewer system by comparing regulator critical elevations (stormwater outlet weir, emergency outlet weir) to those tide elevations.

### Regulators and Interceptors
There are 15 interceptor systems in Philadelphia's Combined Sewer System:

Acronym|Meaning                     |Acronym|Meaning 
----|-------------------------------|----|--------------------------------
CCHL|Cobbs Creek High Level         |P|Pennypack
CCLL|Cobbs Creek Low Level          |S|Somerset
CSES|Central Schuylkill East Side   |SWMG|Southwest Main Gravity
CSWS|Central Schuylkill West Side   |T|Tacony
LDLL|Lower Delaware Low Level       |O|Oregon Ave                       
LFLL|Lower Frankford Low Level      |UFLL|Upper Frankford Low Level
LSES|Lower Schuylkill East Side     |LSWS|Lower Schuylkill West Side
UDLL|Upper Delaware Low Level                                      

A total of **181** regulators were included in this analysis. The list of regulators was based on the regulators that were 'used in overflow total' in the CAPTURE program input file.

### Regulator Critical Elevations 
To intercept sewage, each regulator chamber is incorporated with a dam-like structure, such as static dam, sluice gate, and tide gate, which diverts dry weather flow and a small amount of wet weather flow to the interceptor conduits, and lets extra amount of wet weather flow discharge through the Stormwater Outlet (SWO) to the outfalls.  
For hydraulic-controlled sluice gate type regulators, the critical elevation is set to the stormwater outlet weir crest since all gates are kept shut and act as static dams. For computer-controlled regulators, incl. D02, D03, D05, D07, D09, D11, D15, and F25, the gate opens when trunk level is above the setpoint AND tide level is below the setpoint (in order to prevent backflow). Therefore, the gate acts as a dam at these regulators, and the computer setpoint is the critical elevation. For all other types of regulators, physical dam elevations are used. Plans and site modification notes were reviewed to determine the existence of a tide gate at each regulator.  
Some regulators also include an Emergency Overflow Outlet (EOO) that allows discharge during extreme high flows, or when the tide gate is blocked due to high tides. Similarly, plans and site modification notes, incorporated with videos from the 2015 survery, were reviewed to determine if flap gates existed. 
Regulator node invert elevations, SWO inlet offsets and EOO inlet offsets were extracted from the master sheet (SWMM5_LTCPU_WWMP_Macro_20160425_SystemWide.xlsm). SWO and EOO elevations are then calculated by adding the inlet offset to the regulator node invert elevation. Hydraulic-controlled Sluice gate type regulators were checked/adjusted to ensure the proper SWO is used. The SWO elevations of computer controlled regulators were set to the setpoint, which is acquired from the OUTFALL tab of the master sheet.  

### Regulator Distance from the WPCP  
The distance between a regulator and its downstream WPCP serves as an useful index for sorting regulators in an interceptor system. Plotting regulator critical elevations along the distance provides a visual check to find clusters of regulators that could be potentially impacted by high tide and Sea-level-rise. 
The distances were determined based on the Pipedata file (Pipedata_2016_05_18.xlsx). First, the most upstream node on interceptor was identified for each ‘branch’. Then, the downstream nodes/links were traced recursively until WPCP is reached.  Next, the access point of each regulator on the interceptor were identified, and the accumulated conduit lengths between the regulator access point and the downstream WPCP were calculated, which is the distance for the regulator. For regulators close to the interceptor, the trunk length between regulator and interceptor were ignored. For regulators far away from interceptors, the distances were determined by the Utility Network Analyst Tool in ArcGIS. Relief structures (R sites) were not traced since most of them are not directly connected to tidal waters.  

### Critical Tide Elevations
**MHHW**: Mean Higher High water, the average of the higher high water height of each tidal day observed over the National Tidal Datum Epoch. For PHL, the MHHW for 2015 is 3.59ft in NAVD88 datum, and -1.04ft in city datum.  
Based on the CUSP SLR study, the projected tide elevations in 2085 is 7.72 ft (NAVD88), and MLLW (Mean Lower Low water) is 1.03ft (NAVD88). (subject to change)

**Highest Obs**: NOAA-published highest observed sea level on record (7.53 Ft NAVD88,  Oct 30, 2012 08:00).  

### Useful Acronyms

Acronym|Meaning                     |Acronym|Meaning 
----|-------------------------------|----|--------------------------------
CDF|Cumulative Distribution Function|SWO|Stormwater Outlet weir elevation
Reg|Regulator                       |EOO|Emergency Overflow Outlet weir elevation
CUSP|Climate & Urban Systems Parternership|CC|Computer-Controlled

### Results

```{r, echo = FALSE}
# read full dataset
csv = "DamData.csv"
d <- read.csv(csv,header = T)
library(ggplot2)

#fluidPage works better for inline apps, the width is set to equal to the text width
fluidPage(
    fluidRow(
        column(width=12,
               # add checkbox for all interceptors
               checkboxGroupInput(inputId = "interceptor",
                                  label = "Choose interceptors:",
                                  choices = levels(d$Interceptor),
                                  selected = levels(d$Interceptor),
                                  inline = T)
               ),
        column(width=12,
               # add select/deselect all button
               actionButton(inputId = "selectall", 
                            label="Select/Deselect all")
               ),
        column(width=6,
               # add x axis range slider bar
               sliderInput(inputId = "xrange",
                           label = "x-axis",
                           min=0, max=100,
                           value = c(0,100),
                           round = 1,
                           dragRange = T,
                           step=2)
               ),
        column(width=6,
               # add y axis range slider bar
               sliderInput(inputId = "yrange",
                           label = "y-axis",
                           min=-40,max=400,
                           value = c(-10,350),
                           round = 1,
                           dragRange = T,
                           step=2)
               ),
        column(width=4,textInput(inputId = "anno_label",
                                 label="Annotation:")),
        column(width=4,numericInput(inputId = "anno_value",
                                    label="Elev. (ft) NAVD88",
                                    value = NULL)),
        column(width=2,actionButton(inputId = "anno_add",
                                    label="Add")),
        column(width=2,actionButton(inputId = "anno_reset",
                                    label="reset"))
    ),
    # align the add and reset buttons
    tags$style(type='text/css',"#anno_add {width:100%; margin-top: 25px;}"),
    tags$style(type='text/css',"#anno_reset {width:100%; margin-top: 25px;}"),

    # this is an extra div used ONLY to create positioned ancestor for tooltip
    # we don't change its position
    div(
        style = "position:relative",
        plotOutput('p1', height = '500px',
                   hover = hoverOpts("plot_hover",
                                     delay = 100, 
                                     delayType = "debounce")),
        uiOutput("hover_info1")
    ),
    plotOutput('p2',height = '500px'),
    fluidRow(
        column(width=5,
               selectizeInput(inputId = "interceptorSel",
                              label = "Choose An interceptor:",
                              multiple = F,
                              choices = levels(d$Interceptor),
                              selected = levels(d$Interceptor)[1])
              ),
        column(width=5,
               selectInput(inputId="actualDist",
                           label = "Use actual distance?",
                           multiple = F,
                           choices=c("Actual distance","Even distance"),
                           selected = "Even distance")
              )
    ),
    div(
        style = "position:relative",
        plotOutput('p3',height = '500px',
                   hover = hoverOpts("plot_hover", delay = 100, delayType = "debounce")),
        uiOutput("hover_info3")
    ),
    dataTableOutput('t1')
)

# separate ui and server
    
## add selectall functionality
observeEvent(input$selectall,{
    if (input$selectall %% 2 != 0) {
        updateCheckboxGroupInput(session,
                                 inputId = "interceptor",
                                 label = "Choose interceptors:",
                                 choices = levels(d$Interceptor),
                                 selected = levels(d$Interceptor)[1],
                                 inline = T)
    } else {
        updateCheckboxGroupInput(session,
                                 inputId = "interceptor",
                                 label = "Choose interceptors:",
                                 choices = levels(d$Interceptor),
                                 selected = levels(d$Interceptor),
                                 inline = T)
    }
})

## adjust yrange when interceptor changes
observe(
    if (length(input$interceptor)!=0) {
        updateSliderInput(session,
                          inputId = "yrange",
                          label = "y-axis",
                          min=-40,
                          max=400,
                          value = c(floor(min(d.sub.ecdf()$Dam_Elev_NAVD)),
                                    ceiling(max(d.sub.ecdf()$Dam_Elev_NAVD))),
                          step=2)
    }else{
        updateSliderInput(session,
                          inputId = "yrange",
                          label = "y-axis",
                          min=-40,
                          max=400,
                          value = c(-10,350),
                          step=2)
    }
)

# get the subset dataset
d.sub.ecdf <- reactive(
    if (length(input$interceptor)!=0) {
        d.sub <- subset(d,d$Interceptor%in%input$interceptor)
        ranks <- rank(d.sub$Dam_Elev_NAVD, ties.method='max')
        quantiles <- (ranks / (max(ranks, na.rm=TRUE)+1)) * 100
        data.frame(d.sub,cdf=quantiles)
    } else {
        cbind(d[0,],cdf=as.data.frame("cdf")[0,])
    }
)

# create annotations
anno <- reactiveValues(
    label=c("MHHW 2085","MLLW 2085","MHHW 2015","Highest Obs"),
    value=c(7.72,1.03,3.59,7.53),
    vjust=c(-0.5,1.5,-0.5,1.5)
)

# allow user to add annotations
observeEvent(input$anno_add,
             if (!is.null(input$anno_label) & !is.null(input$anno_value)) {
                 anno$label <- c(isolate(anno$label), input$anno_label)
                 anno$value <- c(isolate(anno$value), input$anno_value)
                 anno$vjust <- c(isolate(anno$vjust), -0.5)
             }
)
# allow user to reset annotations
observeEvent(input$anno_reset,{
    anno$label <- c("MHHW 2085","MLLW 2085","MHHW 2015","Highest Obs.(Oct 30,2012 08:00)")
    anno$value=c(7.72,1.03,3.59,7.53)
    anno$vjust=c(-0.5,1.5,-0.5,1.5)
})
#!# To use plotly in ggplot, replace the following commands:
#     renderPlot->renderPlotly
#     plotOutput->plotlyOutput
#     also, wrap the ggplot object with ggplotly()

my.theme <- theme(plot.title = element_text(size=20, face="bold",
                                margin = margin(10, 0, 10, 0)),
                  panel.background=element_rect(fill='transparent',
                                                color='darkgray',size=0.5),
                  panel.grid.major=element_line(colour = 'gray',size = 0.2),
                  panel.grid.minor=element_line(colour = 'gray',size=0.1),
                  plot.title=element_text(size = rel(1.3)),
                  axis.title = element_text(size = rel(1.3)),
                  axis.text=element_text(size = rel(1.3)))

output$p1 <- renderPlot({
    validate(
        need(input$interceptor, 'Check at least one interceptor!')
    )
    ggplot(d.sub.ecdf(),aes(y=Dam_Elev_NAVD, x=cdf))+
        geom_line(color='blue',size=0.5)+
        geom_point(aes(color=Interceptor,shape=Interceptor),size=3,stroke=1)+
        scale_shape_manual(values=1:nlevels(d.sub.ecdf()$Interceptor))+
        labs(x='CDF (% less or equal to)',
             y='Dam Elevation (ft, NAVD88)',
             title='Interactive CDF plots for dam elevations')+
        my.theme+
        coord_cartesian(xlim = input$xrange,ylim=input$yrange)+
        geom_hline(yintercept = anno$value,
                   linetype=1:length(anno$label),
                   color=1:length(anno$label),
                   size=1)+
        geom_text(data=data.frame(anno$label,anno$value, anno$vjust),
                   aes(x=rep(input$xrange[2],length(anno$label)),
                       y =anno$value,
                       label=anno$label),
                   vjust=anno$vjust,
                   hjust=1,  #right align
                   size=5,
                   check_overlap = T)
})

output$hover_info1 <- renderUI({
    hover <- input$plot_hover
    point <- nearPoints(d.sub.ecdf(), hover, xvar= "cdf",yvar="Dam_Elev_NAVD", threshold = 5, maxpoints = 1, addDist = TRUE)
    if (nrow(point) == 0) return(NULL)

    # calculate point position INSIDE the image as percent of total dimensions
    # from left (horizontal) and from top (vertical)
    left_pct <- (hover$x - hover$domain$left) / (hover$domain$right - hover$domain$left)
    top_pct <- (hover$domain$top - hover$y) / (hover$domain$top - hover$domain$bottom)

    # calculate distance from left and bottom side of the picture in pixels
    left_px <- hover$range$left + left_pct * (hover$range$right - hover$range$left)
    top_px <- hover$range$top + top_pct * (hover$range$bottom - hover$range$top)

    # create style property fot tooltip
    # background color is set so tooltip is a bit transparent
    # z-index is set so we are sure are tooltip will be on top
    style <- paste0("position:absolute; z-index:100; background-color: rgba(245, 245, 245, 0.85); ",
                    "left:", left_px + 2, "px; top:", top_px + 2, "px;")

    # actual tooltip created as wellPanel
    wellPanel(
        style = style,
        p(HTML(paste0("<b> Regulator: </b>", point$Regulator, "<br/>",
                      "<b> Type: </b>", point$Type, "<br/>",
                      "<b> SWO: </b>", point$Dam_Elev_NAVD, "<br/>",
                      "<b> EOO: </b>", point$EOO_Elev_NAVD, "<br/>"))
          )
    )
})

# Fig.2
output$p2 <- renderPlot({
    validate(
        need(input$interceptor, 'Check at least one interceptor!')
    )
    #manually calculate the quantile
    f <- function(x) {
        r <- quantile(x, probs = c(0.00, 0.25, 0.5, 0.75, 1.00))
        names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
        r
    }
    ggplot(data=d.sub.ecdf())+
        # add horizental bars on the end of whiskers
        stat_summary(aes(x=Interceptor,y=Dam_Elev_NAVD,fill=Interceptor),
                     fun.data=f, geom = "errorbar", width = 0.4) +
        # extend whiskers to the min and max and no outlier
        stat_summary(aes(x=Interceptor,y=Dam_Elev_NAVD,fill=Interceptor),
                     fun.data=f, geom="boxplot")+
        labs(title="Stats of regulator dam elevations, by interceptor",
             x="Interceptors",
             y="Dam Elevation, ft NAVD88")+
        geom_hline(yintercept = anno$value,
                   linetype=1:length(anno$label),
                   color=1:length(anno$label),
                   size=1)+
        geom_text(data=data.frame(anno$label,anno$value, anno$vjust),
                  aes( x = rep(0.25,length(anno$label)),
                       y = anno$value,
                       label=anno$label),
                  vjust=anno$vjust,
                  hjust=0,  #right align
                  size=5,
                  check_overlap = T)+
        my.theme +
        theme(legend.position="none")
})

## fig.3
# get the subset dataset
d.sub <- reactive({
    tmp <- subset(d,d$Interceptor%in%input$interceptorSel)
    tmp <- tmp[order(tmp$Distance,na.last = NA),]
    tmp$rank <- seq_along(tmp$Regulator)
    tmp
})

output$p3 <- renderPlot({
    if (input$actualDist=="Actual distance") {
        xvar <- "Distance"
        xlab <- "Distance from WPCP, miles"

    }else{
        xvar <- "rank"
        xlab <- "Regulators, ordered by the distance from WPCP"
    }
  gg <- ggplot(d.sub())+
        # dam elev vs. dist plot, use green and red for tide gate yes and no
        ## line plot
        geom_line(aes(x=d.sub()[,xvar],
                      y=Dam_Elev_NAVD),
                  size=1, linetype=3)+
        ## point plot
        geom_point(aes(x=d.sub()[,xvar],
                       y=Dam_Elev_NAVD,
                       color=factor(TideGate),
                       shape="1"),
                   size=4, stroke=2)+
        # EOO elev vs. dist plot, use green and red for tide gate yes and no
        geom_point(aes(x=d.sub()[,xvar],
                       y=EOO_Elev_NAVD,
                       color=factor(FlapGate),
                       shape="4"),
                   size=4, stroke=2)+
        scale_colour_manual(name='By Color',
                            # specify colors by value instead of levels
                            # good for cases when one level is empty
                            values = c('0'='red','1'='green'),
                            labels = c('0'='No Tide/Flap Gate',
                                       '1'='Has Tide/Flap Gate'))+
        scale_shape_manual(name='By Shape',
                           values = c(1,4),
                           breaks=c(4,1),
                           labels = c('Emergency Overflow Weir',
                                      'SWO Dam'))+
        geom_hline(yintercept = anno$value,
                   linetype=1:length(anno$label),
                   color=1:length(anno$label),
                   size=1)+
        geom_text(data=data.frame(anno$label,anno$value, anno$vjust),
                  aes(x=rep(max(d.sub()[,xvar]),length(anno$label)),
                      y =anno$value,
                      label=anno$label),
                  vjust=anno$vjust,
                  hjust=1,  #right align
                  size=5,
                  check_overlap = T)+
        labs(x=xlab,
             y='Elevation (ft, NAVD88)',
             title='Interactive plot for regulator elevations')+
        my.theme

    # add a secondary axis for regulator if real distance is used.
    if (input$actualDist=="Actual distance") {
        yrng <- ggplot_build(gg)$panel$ranges[[1]]$y.range
        gg <- gg + geom_text(data=data.frame(),
                             aes(x = d.sub()$Distance,
                                 y = 1.1*yrng[2],
                                 label = d.sub()$Regulator),
                             size=4,
                             angle=90,
                             hjust=0.5,
                             check_overlap = T)
    }else{
        gg <- gg + scale_x_continuous(
                        breaks=d.sub()$rank,
                        labels=d.sub()$Regulator)+
               theme(axis.text.x = element_text(angle=90,vjust=0.5))
    }
  gg
})

output$hover_info3 <- renderUI({
    if (input$actualDist=="Actual distance") {
        xcol <- "Distance"
    }else{
        xcol <- "rank"
    }

    hover <- input$plot_hover
    point <- nearPoints(d.sub(),hover, xvar=xcol, yvar="Dam_Elev_NAVD", threshold = 5, maxpoints = 1, addDist = TRUE)

    if (nrow(point) == 0) return(NULL)

    # calculate point position INSIDE the image as percent of total dimensions
    # from left (horizontal) and from top (vertical)
    left_pct <- (hover$x - hover$domain$left) / (hover$domain$right - hover$domain$left)
    top_pct <- (hover$domain$top - hover$y) / (hover$domain$top - hover$domain$bottom)

    # calculate distance from left and bottom side of the picture in pixels
    left_px <- hover$range$left + left_pct * (hover$range$right - hover$range$left)
    top_px <- hover$range$top + top_pct * (hover$range$bottom - hover$range$top)

    # create style property fot tooltip
    # background color is set so tooltip is a bit transparent
    # z-index is set so we are sure are tooltip will be on top
    style <- paste0("position:absolute; z-index:100; background-color: rgba(245, 245, 245, 0.85); ",
                    "left:", left_px + 2, "px; top:", top_px + 2, "px;")

    # actual tooltip created as wellPanel
    wellPanel(
        style = style,
        p(HTML(paste0("<b> Regulator: </b>", point$Regulator, "<br/>",
                      "<b> Type: </b>", point$Type, "<br/>",
                      "<b> SWO: </b>", point$Dam_Elev_NAVD, "<br/>",
                      "<b> EOO: </b>", point$EOO_Elev_NAVD, "<br/>"))
        )
    )
})

# # add data table
output$t1 <- renderDataTable({
    validate(
        need(input$interceptor, 'Check at least one interceptor!')
    )
    library(dplyr)
    d.sub.tbl <- d.sub.ecdf() %>%
        group_by(Interceptor) %>%
        summarize(
            `Min Elev. (ft NAVD88)`=round(min(Dam_Elev_NAVD),2),
            `Mean Elev. (ft NAVD88)`=round(mean(Dam_Elev_NAVD),2),
            `Max Elev. (ft NAVD88)`=round(max(Dam_Elev_NAVD),2),
            `Total Regulators`=length(Dam_Elev_NAVD),
            `Regulators below MHHW_2015 (3.59ft)` = paste0(length(which(Dam_Elev_NAVD<=3.59)),"  (",round(length(which(Dam_Elev_NAVD<=3.59))/(length(Dam_Elev_NAVD))*100,0),"%)"),
            `Regulators below Highest.Obs 2012/10/30 8:00 (7.53ft)` = paste0(length(which(Dam_Elev_NAVD<=7.53)),"  (",round(length(which(Dam_Elev_NAVD<=7.53))/(length(Dam_Elev_NAVD))*100,0),"%)"),
            `Regulators below MLLW_2085 (1.03ft)` =paste0(length(which(Dam_Elev_NAVD<=1.03)),"  (",round(length(which(Dam_Elev_NAVD<=1.03))/(length(Dam_Elev_NAVD))*100,0),"%)"),
            `Regulators below MHHW_2085 (7.72ft)` =paste0(length(which(Dam_Elev_NAVD<=7.72)),"  (",round(length(which(Dam_Elev_NAVD<=7.72))/(length(Dam_Elev_NAVD))*100,0),"%)")
        )

d.sub.total <- d.sub.ecdf() %>%
        summarize(
            `Interceptor`="Subtotal",
            `Min Elev. (ft NAVD88)`=round(min(Dam_Elev_NAVD),2),
            `Mean Elev. (ft NAVD88)`=round(mean(Dam_Elev_NAVD),2),
            `Max Elev. (ft NAVD88)`=round(max(Dam_Elev_NAVD),2),
            `Total Regulators`=length(Dam_Elev_NAVD),
            `Regulators below MHHW_2015 (3.59ft)` = paste0(length(which(Dam_Elev_NAVD<=3.59)),"  (",round(length(which(Dam_Elev_NAVD<=3.59))/(length(Dam_Elev_NAVD))*100,0),"%)"),
            `Regulators below Highest.Obs 2012/10/30 8:00 (7.53ft)` = paste0(length(which(Dam_Elev_NAVD<=7.53)),"  (",round(length(which(Dam_Elev_NAVD<=7.53))/(length(Dam_Elev_NAVD))*100,0),"%)"),
            `Regulators below MLLW_2085 (1.03ft)` =paste0(length(which(Dam_Elev_NAVD<=1.03)),"  (",round(length(which(Dam_Elev_NAVD<=1.03))/(length(Dam_Elev_NAVD))*100,0),"%)"),
            `Regulators below MHHW_2085 (7.72ft)` =paste0(length(which(Dam_Elev_NAVD<=7.72)),"  (",round(length(which(Dam_Elev_NAVD<=7.72))/(length(Dam_Elev_NAVD))*100,0),"%)")
        )
    d.out <- rbind(d.sub.tbl,d.sub.total)
})
```

### Discussion 
The CDF and box-whisker plots indicate that **79** out of the 181 regulators (44%) have dam elevations lower than the MHHW 2015, and most of which are in the Delaware and Schuylkill interceptor systems, many have been protected by tide gates. Based on the 2085 projection, it's estimated that the number would increase to 104 (57%). While tide gates provide backflow prevention, they also create surcharging issues during high tides . 
